spring:
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8538
        project-id: our-project

queueconfig:
  shared-pubsub-project: shared-project
  ras-rm-pubsub-project: REPLACEME

caserefgeneratorkey: abc123